# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-14 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180913_0615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='description',
            new_name='ccy',
        ),
        migrations.RenameField(
            model_name='balance',
            old_name='isin',
            new_name='fund',
        ),
        migrations.RenameField(
            model_name='balance',
            old_name='security_type',
            new_name='institution',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='cash_flow',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='date',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='price',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='settles',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='ticker',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='trade',
        ),
    ]
