# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-05 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180914_0712'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='')),
                ('report_id', models.IntegerField()),
                ('client_id', models.IntegerField()),
            ],
            options={
                'db_table': 'comments_data',
            },
        ),
        migrations.AlterUniqueTogether(
            name='commentsdata',
            unique_together=set([('report_id', 'client_id')]),
        ),
    ]
